### ISSUE TITLE
Request for specification / detail re. protocol and units

### ISSUE THREAD

**Issue by daniel-j-h** [scanse/sweep-sdk-cpp#2]
I'm working on converting this SDK to a API- and ABI stable C library with a C++11 convenience header on top and FFI bindings for Python and Haskell (and maybe other FFI bindings and a websocket service) every now and then on the weekend and evenings when I can spare some time.

It would be great to make the laser's specification and / or details wrt. the protocol and the units available:
https://github.com/scanse/sweep-sdk-cpp/blob/e74780f92d0b195d00aff24c342dc519c19e82da/include/sweep/sweep_protocol.h

without a device I can otherwise only guess and hope for the best.

Could you make the spec. you implemented the protocol against available? And if not could you at least add comments to all of the protocol's fields describing their unit and raison d'être - most importantly the user-facing ones such as scan_packet, info_version, info_motor.

Thanks!

**Comment by kent-williams** [comment]
Hi Daniel,

I've emailed you
