### ISSUE TITLE
Using c++11 & support for VS

### ISSUE THREAD

**Issue by MikeGitb** [scanse/sweep-sdk-cpp#3]
From the cmake file I'm inferring that you 

  a) expect a c++11 compiler (although the sdk seems to compile work with c++03 quite fine) and 
  b) that you are planning to support windows (which would be great). 

In that regard, I was wondering if there is a special reason, why you seem to avoid standardized c++11 functions in favor of linux specific IO calls (like ptherads instead of `std::thread`, `usleep` instead of `std::this_thread::sleep_for`, or `clock_gettime` instead of e.g. `std::system_clock::now()` ).

If there is no special reason for it, I could offer a c++11 patch that would remove all of the platform specific code (except for the serial interface of course)

**Comment by kent-williams** [comment]
Hi Mike,

One of our community members sparked the idea of a much better route for the sweep sdk and has already written the core of it. It's a C99 library with optional C++11 header. We'll have bindings for other languages such as python, js, and java. We should be releasing it in a few weeks. 

This current sdk didn't quite get to proper C++11 spec, my apologies!

-Kent

**Comment by MikeGitb** [comment]
Hi Kent,

thanks for the quick response. The way I understand it, it will take a few more months before the sweep hardware will be available, so I'm in no rush. I only asked, because I'm interested in using this sdk on windows with visual studio and using c++11seemed like a good and simple way to make the remaining code cross-platform. But as you are targeting embedded systems I understand if you give priority to c99 + linux.
Anyway, it will be simple to write my own portable binding if necessary, so no problem.

**Comment by daniel-j-h** [comment]
Hey @MikeGitb - here's a preview of what my basic examples currently look like:

```c++
#include <iostream>
#include <sweep/sweep.hpp>

int main() try {
  sweep::sweep device;

  device.start_scanning();

  for (auto n = 0; n < 10; ++n) {
    auto scan = device.get_scan();

    for (auto sample : scan.samples)
      std::cout << "angle " << sample.angle << " distance " << sample.distance << " signal strength " << sample.signal_strength << "\n";
  }

} catch (const sweep::device_error& e) {
  std::cerr << "Error: " << e.what() << std::endl;
}
```

Stay tuned!

**Comment by MikeGitb** [comment]
@daniel-j-h: Looks nice. Just to be clear: Will this library compile with Visual studio 2015?

**Comment by daniel-j-h** [comment]
The serial communication part is POSIX specific at the moment, but extending this to any platform should be as easy as to implement a Windows-specific serial read / write / flush function.

**Comment by MikeGitb** [comment]
Maybe you can integrate the code from this repo as it seems to already provide those functions.

**Comment by MikeGitb** [comment]
@daniel-j-h: Has there been any update with regard to your new lib? Is there a preview available?

**Comment by daniel-j-h** [comment]
Ah sorry for not updating this issue: check out https://github.com/scanse/sweep-sdk there are also some screenshots of the realtime viewer and some density based clustering.

There are some issues open in that repository wrt. polishing up the SDK, making it work on macOS and Windows etc. see [the list of tickets](https://github.com/scanse/sweep-sdk/issues).

- macOS https://github.com/scanse/sweep-sdk/issues/1
- Windows https://github.com/scanse/sweep-sdk/issues/5

This is mainly blocked by me not having a macOS or Windows environment (or experience :P) to implement the needed functions against. If you want to lend a hand I'm more than glad to guide you through what needs to be done.

It's mainly having `read` and `write` functions for the serial device and then a platform specific sleep function: https://github.com/scanse/sweep-sdk/tree/master/libsweep

Check `serial.h` and `time.h` for the interfaces a new platform has to implement. Check the `serial_unix.c` and `time_unix.c` files for a UNIX-specific implementation of those interfaces.

The rest should fall in place automatically.

**Comment by MikeGitb** [comment]
@Daniel-j-h: Looks good, thank you.

While I'd be happy to lend a hand, I'm not sure, of how much help I could be as I've no experience with using the serial interface on windows and don't have the actual HW to test my code.
